before_script:
  - "cp config/database-ci.yml config/database.yml"
  - "psql -c 'create database gars_du_nord_bergerac_test;' -U postgres"
  - "sh -c 'bundle install && bundle exec rake db:create db:migrate'"
env:
  - DB=postgresql
git:
  submodules: false
language: ruby
rvm:
  - 1.9.3
script: 'bundle exec rspec spec'
