before_script:
  - cp config/database-ci.yml config/database.yml
  - psql -c 'create database gars_du_nord_bergerac_test;' -U postgres
  - sh -c 'bundle install && bundle exec rake db:create db:migrate'
env:
  global:
    - DB=postgresql
git:
  submodules: false
language: ruby
rvm:
  - 1.9.3
script: bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: VPK7TbB9Wlx0Y++K+p1TmEpLNvk3gJtouTvK7VCq39gN4p6Thjm2uiiblPlfttMauKbN1gTJzbr7daGz2MCgwFwvZ8Cg1syCH39m5ORfFiGG4XvorGyt5rMq2Hf6zc7YXymXUz1QMiNZ2KNijBcRPdEg+iaQh9OCit2Ta9gYKeU=
  app: garsdunordbergerac-org
  on:
    repo: garsdunordbergerac/garsdunordbergerac
