before_script:
  - cp config/database-ci.yml config/database.yml
  - psql -c 'create database gars_du_nord_bergerac_test;' -U postgres
  - sh -c 'bundle install && bundle exec rake db:create db:migrate'
env:
  global:
    - DB=postgresql
git:
  submodules: false
language: ruby
rvm:
  - 1.9.3
script: bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: O1+4B3uMLnbgZC15YeEOfhMURWJaMj8i6YpTtem5kXDOgnDc4XWXK55qzgF1B7k5lZTivXdm9r1qYW6EZUjl2FmHapOOUUSACn1xZtY/hDwhbQ3c0dfzx28BbM4Peu65fgYfEgMG9Uf3pH4FtPoCvMbZq0Zsf56qIfbvGn4JN1Q=
  app: garsdunordbergerac-org
  on:
    repo: garsdunordbergerac/web
  strategy: git
  run:
    - 'rake db:migrate'
